# Generated by Django 3.0.6 on 2020-05-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creationDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
