# Generated by Django 3.0.5 on 2020-05-21 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ChatBot', '0002_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
