# Generated by Django 3.0.6 on 2020-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0003_ticket_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketID',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
